version: '3.3'
services:
  dbMysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'friedeuser'
      MYSQL_PASSWORD: 'arduino19!'
      MYSQL_ROOT_PASSWORD: 'arduino19#'
    ports:
      - '3306:3306'
    expose:
      - '3306'